README.md
spec/README.md

This should make the spec easier to find and read. Now the specification lives entirely within the spec/ directory and other supplemental material lives outside.

Split specification into separate files.

---

README.md
spec/README.md
spec/field_types.md
spec/predicates/link.md
spec/predicates/provenance.md
spec/predicates/spdx.md

Add a new Statement `type` field that indicates the schema version,
and use an unversioned MediaType in the Envelope `payloadType` field.
Reasoning:
-   This makes the Statement self-describing, which aids readability.
-   Not all envelopes authenticate the payload type. Since we want the
layers to be independent, we should include the schema version
inside to protect against this.
-   MediaType is the standard way of indicating encoding; URI is
uncommon for that purpose.
-   Most formats include a version inside the payload (e.g. PDF or
JsonSchema) and have an unversioned MediaType. We do the same.
-   Removing the encoding from the type URI (i.e. removing "-json")
allows policy engines to be encoding-agnostic.
-   The existing in-toto format (link and layout) already use a `type`
field, …

Add `Statement.type` and use MediaType in envelope.

---

README.md
spec/README.md
spec/predicates/link.md
spec/predicates/provenance.md
spec/predicates/spdx.md
spec/versioning.md

* Document the versioning convention (#4).
* Provide an extension mechanism based on URI-named fields (#8).
* State that consumers MUST ignore unrecognized fields, which is required by both of the above.
* Remove `mediaType` and `tags` from the Predicate spec since those two fields are not yet ready to be standardized (#19).
@TomHennen to review

Document convention for versioning and extensions, remove mediaType and tags

---

spec/predicates/provenance.md

@TomHennen does this address your concerns?

Provenance: clarify `environment`.

---

spec/predicates/link.md

It is not yet clear that the Link schema is finalized. Open questions:
- Should "_type" be optional?
- Should "products" be removed in favor of "subject"?
Since we are not yet decided, the 0.1 version makes this more clear.
NOTE: This goes against semantic versioning, but no one has depended on
this yet, and we do want to use the 0.x series to indicate "in
development", so it seems like a decent enough tradeoff to make at this
point.

Switch Link to v0.1 (was v1).

---

spec/predicates/link.md

Omit redundant fields in the predicate, add pseudocode for how to convert to an old-style link, and bump the version number to 0.2.
- _type: Can be inferred from predicateType.
- products: We now define that this is equivalent to subject, rather than saying subject is some ambigous combination of products and/or materials. Although this isn't always a perfect fit, doing so makes it much more clear how to interpret the predicate and fit it into the existing in-toto ecosystem.
@SantiagoTorres What do you think of this conversion rule? I'm updating ITE-6 now and can use this once it's merged.

Link v0.2: omit `_type` and `products`; add conversion.

---

spec/predicates/provenance.md

A build invocation ID is a very useful, general concept that almost all
build systems have. It allows one to look up associated logs and perform
other ad-hoc analysis. Therefore, it makes sense to add it as a standard
field.

Provenance: Add buildInvocationId, bump to v0.1.1.

---

spec/predicates/provenance.md

Previously, the examples were unclear as to who generates the provenance.

Provenance: clarify what the builder means.

---

README.md

ITE-6 is now merged, so we should link to the published version instead of the PR.

Update ITE-6 link to proper ITE document

---

README.md

"main" is now the default branch name, and it's also a bit friendlier than "master".
Leaving "master" in the curl example, as the branch hasn't currently been renamed in the curl/curl-docker repo and thus "master" is correct here, from a URL perspective.

README: Replace "master" branch names with "main" in examples

---

spec/README.md

Fixes markdownlint MD049 check (#83).

lint: Use consistent emphasis style

---

spec/README.md

The location for the linked content within the slsa-framework/slsa repository
has moved to a new place which is now rendered as part of slsa.dev, therefore
update the link to point to the rendered page https://slsa.dev/attestation-model

Link to attestation model description on slsa.dev

---

spec/bundle.md

Clarify the naming convention to be unambiguous when a single bundle "concerns" a single artifact but has attestations for other dependent artifacts.
Remove the recommendation for `multiple.intoto.jsonl`. In its absence, implementations can choose a name that makes sense for that use case.
Fixes #107.

Clarify bundle naming convention

---

spec/bundle.md

Current link doesn't work, README.md is a sibling to bundle.md.

bundle: fix link to monotonic principle

---

spec/predicates/scai.md

The Software Supply Chain Attribute Integrity, or SCAI (pronounced "sky") data format is designed to capture functional attribute and integrity information about software artifacts and their supply chain. SCAI data can be associated with executable binaries, statically- or dynamically-linked libraries, software packages, container images, software toolchains, and compute environments.
Why do we need this? Existing supply chain data formats do not capture any information about the security functionality or
*behavior* of the resulting software artifact, nor do they provide sufficient evidence to support any claims of integrity of the supply chain processes they describe. The SCAI data format is designed to bridge this gap.
This PR addresses #76 . An example use case for SCAI is described …

Add support for the SCAI predicate

---

README.md

Fixes https://github.com/in-toto/attestation/issues/122 - updates the link to the SLSA Attestation Model docs.

Fix SLSA Attestation model link

---

spec/field_types.md

This is the first digest algorithm that is not a straight cryptographic hash over a blob of data.
Decisions:
- Use the name `goModuleH1` instead of `goDirhash` or similar because (a) it makes it more clear that this is only for go modules and (b) to allow future H2, H3, etc. to be expressed in the same DigestSet.
- Use hex encoding instead of base64, since that is what we use elsewhere.
See #28 for background.

Add `goModuleH1` to the list of predefined digests

---

spec/v1.0-draft/README.md

There are cases where unrecognised fields SHOULD reject unrecognised fields, rather than ignoring them. This is true for the externaleParameters field in SLSA provenance v1 and the summary of the parsing rules included in that specification were recently updated to clarify. https://github.com/slsa-framework/slsa/pull/628
This change updates the guidance here to match.
Fixes: #138

Update parsing rules for unrecognized fields

---

spec/v1.0-draft/digest_set.md

There are cases where custom digests might be better expressed using different encodings.
refs #130

Specify lowercase-hex encoding for standard algorithms only.

---

spec/v1.0-draft/statement.md

Don't make producers set subject.name if it doesn't mean anything.
This simplifies their workflow and reduces the size & cost of
producing statements when there are a lot of subjects.
Retain option to use '_' for backwards compatibility, could
probably remove that without any harm.
fixes #142

Relax subject name

---

spec/v1.0-draft/digest_set.md

Previously the spec was written specifically for go modules, which always have a single top-level directory entry of the form `name@version`. However, this function is not specific to go and does not need to have a restriction that there is a single `name@version` top-level directory.
Now the spec explains that it is designed but not specifically for go modules, and walks through a detailed example of how to compute. It also better explains how to run the "equivalent" command.
Is this clear? Is it a good idea? I was surprised re-reading the spec that it requires `name@version` since that likely won't apply to other package ecosystems.

Rename `goModuleH1` to `dirHash1` and add better explanation

---

spec/v1.0-draft/statement.md
spec/v1.0-draft/statement.proto

Any minor changes should be backwards compatible so there's no need to identify type in the statement and it could actually be harmful.
Leaving it as is in docs and such because the text could change with point releases.
refs #130

Remove .0 from the _type uri

---

spec/v1.0-draft/README.md

Extension fields no longer recommend using TypeURI as a name since this can cause problems for some users.
Instead we recommend avoiding `.` and `$` and simply advise users to avoid names that may collide, without telling
them how to do so.  Users are encouraged to file an issue to document extensions they're using.
fixes #147.

Update extension fields

---

spec/v1.0-draft/digest_set.md

This adds `gitCommit`, `gitTree`, `gitBlob`, and `gitTag` to the standard algorithms of DigestSet.
The first two commits reformat the algorithm list, while the third commit adds the new algorithm. It may be helpful to review the commits separately. I included an intermediate version using `<dl>` that I think looks worse but I left in for posterity, in case it is preferred.
Fixes #145.

Add gitCommit, gitTree, etc to DigestSet

---

spec/v0.1.0/field_types.md
spec/v1.0-draft/field_types.md
spec/v1.0-draft/scalar_field_types.md

The old link stopped working, it seems like we should link to a specific version.

Fix spdx download location URL

---

spec/predicates/README.md
spec/predicates/runtime-trace.md

This is an early draft of a runtime trace predicate type. We've noted some subsections / fields that need more input.
cc @pxp928 @nadgowdas @jedsalazar

Add runtime trace predicate type

---

spec/versioning.md

The individual versions already indicate how extension fields can be added, and it should be possible to change that method with various versions.  Having versioning.md include that logic also could lead to confusion and disagreement.
fixes #167

Remove extension fields from versioning.md

---

README.md
spec/predicates/README.md
spec/v1.0/README.md
spec/v1.0/statement.md

This PR does three things:
* Fix broken links in documentation
* Add some missing predicate types to docs
* Highlight spec overview in top-level README to make attestation format more easy to find

Minor documentation fixes

---

spec/predicates/spdx.md

This commit contains a suggestion for updating the SPDX predicate specification, to include the version in the `predicateType`.
The motivation for this change is same to the motivation that was mentioned for including the version in the CycloneDX predicate specification which is that it allows a consumer to determine the version without having to parse the predicate itself.

Update SPDX predicate specification

---

spec/v1.0/predicate.md

spec/v1.0/predicate.md linked to 'existing predicate type' but didn't actually define the link

Link to existing predicates from predicate.md

---

spec/v1.0/resource_descriptor.md

Currently, the `ResourceDescriptor` only mandates one of `uri`, `digest`, or `content`. However, some predicates (links for example) and/or the subject field in the Statement should be able to mandate one or more fields separately.

Allow uses of ResourceDescriptor to require fields

---

protos/README.md
protos/in_toto_attestation/predicates/link/v0/link.proto
spec/predicates/link.md
spec/v1/resource_descriptor.md

* Updates materials to use ResourceDescriptor
* Introduces a protobuf definition for the link predicate.

Define v0.3 of the link predicate

---

docs/validation.md
protos/in_toto_attestation/v1/statement.proto
spec/v1/statement.md

Updates statement.proto to use ResourceDescriptor which changes the number of `digest` from 2 to 3.

Use ResourceDescriptor for statement subjects

---

spec/predicates/link.md

Also marks the requirement for material entries.

Require 'subject[*].name' to be unique for links

---

protos/README.md
protos/in_toto_attestation/predicates/provenance/v1/provenance.proto
spec/predicates/provenance.md

Also adds the protobuf definition for the v1 predicate (per https://github.com/slsa-framework/slsa/issues/855).
Fixes #200

Update the SLSA provenance predicate to v1

---

.github/workflows/make-protos.yml

Fixes a bug in our current make-protos.yml file that's causing the language bindings regeneration to fail.

Update supported protoc version in CI

---

protos/in_toto_attestation/v1/resource_descriptor.proto
spec/v1/resource_descriptor.md

This change expands support from objects to all JSON values. This allows maximum flexibility for producers and better matches the implicit reading of the spec many, including the SLSA project, had.
Fixes: #242

Change annotations fields in ResourceDecriptor from objects to values

---

go/v1/resource_descriptor_test.go

The changes in #251 to update the type of the annotation value in a resource descriptor was not reflected in the tests, causing them to fail. Update the tests to use the new annotation value type.
---
I'm not sure why the the follow-on auto-PR to update the generated code #258 did not trigger the [run-go-tests](https://github.com/in-toto/attestation/actions/workflows/run-go-tests.yml) workflow?

fix(tests): fix go tests since #251

---

.github/workflows/run-go-tests.yml

Fixes the issues where an auto-PR to update the generated code https://github.com/in-toto/attestation/pull/258 does not trigger the [run-go-tests](https://github.com/in-toto/attestation/actions/workflows/run-go-tests.yml) workflow.

add missing trigger for push main branch in go-test workflow

---

docs/protos.md
protos/in_toto_attestation/predicates/vsa/v0/vsa.proto
protos/in_toto_attestation/v1/resource_descriptor.proto
protos/in_toto_attestation/v1/statement.proto

We [claim](https://github.com/in-toto/attestation/blob/461c6b92b7f79f4bca73e6c69b68bf6121052221/docs/protos.md) to adhere to the protobuf programming practices, and thus should also follow the [style guide](https://protobuf.dev/programming-guides/style/#message-field-names) there.
The style guide states that message field names should be lower_snake_case, not lowerCamelCase. Our protobuf definitions are somewhat inconsistent, this PR normalises to lower_snake_case for field names in protobuf definitions.
Fixes: #250

Use lower_camel_case consistently for fields in protobuf definitions

---

go/v1/resource_descriptor.go
go/v1/resource_descriptor_test.go
go/v1/statement.go
go/v1/statement_test.go

Fixes #231 
* Create named errors for reuse and testing
* Assert in tests expected named errors
* Add test for subject-specific restriction on subject RD

Update Go tests

---

go/predicates/scai/v0/scai.go
python/in_toto_attestation/predicates/scai/v0/scai.py

This PR adds basic SCAI predicate wrapper/verification APIs for both Go and Python bindings.
We can discuss if it would be more appropriate to push these APIs to the individual in-toto implementations (in-toto-golang and in-toto) once they've added support for v1 attestations.

Add Go and Python bindings for SCAI predicate

---

spec/predicates/README.md
spec/predicates/vuln.md

As a continuation of the discussion initiated in https://github.com/in-toto/attestation/issues/58 and the Slack [thread](https://cloud-native.slack.com/archives/CM46K2VT2/p1689167384025049), I decided to propose a vulnerability scan-specific in-toto predicate.
This ITE-9 document describes a vulnerability predicate type to represent vulnerability reports from the scanners in an "exportable" manner and independently of the format chosen to output the scanning results.
Note that, the fields proposed for this new predicate type are inspired by the [cosign specification for the vulnerability attestations](https://github.com/sigstore/cosign/blob/main/specs/COSIGN_VULN_ATTESTATION_SPEC.md).

vulnerability attestation: ITE-9 specification

---

go/predicates/provenance/v1/provenance.go
go/predicates/provenance/v1/provenance_test.go

This PR adds Validate() functions for the SLSA Provenance v1 Go bindings, per the [SLSA Provenance v1 spec](https://slsa.dev/spec/v1.0/provenance#provenance), as well as basic tests. 
Note: This PR is a blocker for ITE-6/ITE-9 integration in in-toto-golang: https://github.com/in-toto/in-toto-golang/pull/268.

Add Go validator APIs for Provenance v1 predicate

---

python/in_toto_attestation/v1/resource_descriptor.py
python/in_toto_attestation/v1/statement.py

Fixes #300.
My editor made some formatting changes as well, based on the `black` rules -- let me know if you'd prefer to not have these, and I'll limit this PR to just the type fix.

in_toto_attestation/v1: fix type hints

---

.gitignore
python/Makefile

https://github.com/in-toto/attestation/pull/308 checks in a full virtual environment, which we ought to avoid...

Add python venv dir to gitignore

---

docs/new_predicate_guidelines.md

This PR explicitly adds three main common action items that are part of the vetting process for new predicate types:
- updating the list of existing predicates
- adding a proto definition to generate language bindings
- updating the URL redirects for predicateType URIs that are defined within the in-toto.io/attestation namespace
fixes #313

Add common action items for the new predicate vetting process

---

.github/workflows/python.yml

The python CI tests currently run on every single PR and push to main, even if no changes to the Python APIs have been made. This PR limits python testing to changes under the `python/` directory.

Only run python tests for changes to Python APIs

---

go/v1/resource_descriptor.go
go/v1/resource_descriptor_test.go

Since the spec requires digests in a DigestSet to be hex-encoded, this PR enhances the `Validate()` function for the ResourceDescriptor and adds a corresponding test.

Add DigestSet hex encoding validation

---

spec/v1/envelope.md

The examples already show the usage of the filename.
fixes #343

Clarify that the storage specification uses the _file_ name.

---

spec/v1/CHANGELOG.md
spec/v1/README.md
spec/v1/bundle.md
spec/v1/digest_set.md
spec/v1/predicate.md
spec/v1/resource_descriptor.md
spec/v1/statement.md

There are uses for DigestSets that don't involve cryptographic hashes and I don't think we ever meant to preclude those uses?
(This PR motivated by [this discussion](https://github.com/in-toto/attestation/pull/330/commits/e8c06cf62050b96daf4ef356bf382f4680a07be3#r1511872856) and another I've had with @laurentsimon).
Sometimes users have a need to refer to something by some other immutable identifier.  Either because the content can't be hashed traditionally, because it's impractical to hash traditionally, or because they interact with the content through an interface that doesn't expose them to the entirety of the content.
In these situations users may wish to use other identifiers in a DigestSet.  Those users should be careful to understand the trust that they're placing in the …

Clarify that digests don't have to be cryptographic ones.

---

spec/README.md

I missed the 1.0 reference in spec/README.md.  This updates it to 1.1 to match the other docs.

Update link in README to 1.1

---

spec/README.md
spec/versioning.md

This PR adds a short description clarifying _when_ the attestation spec version is rev'd and how that relates to tagged releases.

Clarify versioning and tagged release process

---

spec/predicates/link.md
spec/predicates/test-result.md

There exist two broken links to resource descriptor in the repo pointing to a `/spec/v1.0` directory which doesn't exist. Fixed these references.

Fix broken links to ResourceDescriptor

---

python/Makefile

Also update the makefile to let the user specify their own python binary.
Fixes #369

'check' must be specified explicitly

---

protos/in_toto_attestation/predicates/provenance/v1/provenance.proto

Update the comment to point to the updated location of the v1.0 provenance proto file in the SLSA framework repository
This file was moved to a new location in the repository last month as part of https://github.com/slsa-framework/slsa/pull/939/files#diff-0d74b135d4a3da2b4ed73c88a4566d07e465dd6aee46f46f45e0ffbb7c232128

Update link to SLSA framework proto file

---

go/predicates/scai/v0/scai.go
python/Makefile
python/in_toto_attestation/predicates/scai/v0/scai.py
python/pyproject.toml
spec/predicates/scai.md

Unlike the [recommended naming convention](https://github.com/in-toto/attestation/blob/main/docs/new_predicate_guidelines.md#vetting-process), the SCAI predicate TypeURI has an extra element `/attribute-report`. This may confusingly signal other types of SCAI predicates, which don't exist AFAIK, and is therefore redundant. This PR makes the type URI conform with the expected convention, and bumps the minor version.
Related to #371 .

Simplify SCAI predicate TypeURI

---

protos/in_toto_attestation/predicates/reference/v0/reference.proto
spec/predicates/README.md
spec/predicates/reference.md

Adds the specification of a predicate to address #179.
One question I had was how to express what content the reference contains. I think the current use cases are met by the MIME type, and adding another field to specify this more explicitly would make the predicate more complex. If needed, it can be added in the future in a new version.
Open to feedback!

Add the reference predicate

---

spec/predicates/vulns_02.md

As part of fixing #391 following up #345, removing invocation since it is not part of the spec in the example

fix discrepencies in v0.2 example

---

protos/in_toto_attestation/predicates/vulns/v0.2/vulns.proto
spec/predicates/vulns_02.md

This PR updates the vulns02 protos to rename the `scanner.database` field (to `scanner.db`) and the `scanner_metadata` field (to just `metadata`) to match the vulns02 spec.
Sample generated predicate (with the go library):
```json
{
"scanner": {
"uri": "pkg:github/aquasecurity/trivy@244fd47e07d1004f0aed9",
"version": "0.19.2",
"db": {
"uri": "pkg:github/aquasecurity/trivy-db/commit/4c76bb580b2736d67751410fa4ab66d2b6b9b27d",
"version": "v1-2021080612",
"last_update": {
"seconds": 1737495873,
"nanos": 773202315
}
},
"result": [
{
"id": "CVE-123",
"severity": [
{
"method": "nvd",
"score": "medium"
},
{
"method": "cvss_score",
"score": "5.2"
}
]
}
]
},
"metadata": {
"scan_started_on": {
"seconds": 1737495873,
"nanos": 773202413
},
"scan_finished_on": {
"seconds": 1737495873,
"nanos": …
```

VulnsV2: Add missing invocation to protos and spec

---

MAINTAINERS.md

We've been seeing an increased activity again, and as we work towards in-toto v2, it would be really helpful to have five maintainers again to increase our review throughput. I propose adding @trishankatdatadog (who has agreed) as our fifth maintainer. Trishank is co-author of the original in-toto spec and a current ITSC member.
This PR also recognizes Joshua Lock as an Emeritus maintainer.

Add Trishank as attestation maintainer

---

protos/Makefile
spec/README.md
spec/predicates/README.md
spec/v0.1.0/README.md

This PR fixes a CI error where the Rust code generation fails due to a wrong path in the Makefile. It also fixes three link-related linter errors.

Fix: Rust codegen in CI and Linter errors

---

.github/workflows/run-go-tests.yml

This PR bumps the go version used in the CI tests to 1.23.x, matching the version used to build the Go bindings.

Bump Go version in CI tests
